lib/Toast/ToastContainer.js
lib/Toast/index.js
lib/Toast/types.ts
src/stories/Toast.stories.js

refactor: toast, skip-ci

---

lib/index.js
lib/utils/index.js

feat(utils): noop, skip-ci

---

lib/Icon/CaretDown.js
lib/Icon/Close.js
lib/Icon/Loading/index.js
lib/Icon/Polkadot.js

fix(icon): props

---

lib/styled/Dropdown.js
package.json
yarn.lock

fix: revert dropdown import

---

lib/ConnectWallet/usePolkadotExtension.js

fix: connect wallet use polkadot extension

---

lib/Modal/index.js

feat(modal): width

---

lib/index.js

feat: expose consts

---

lib/Identity/IdentityUser.js
package.json
src/stories/Identity.stories.js
yarn.lock

fix(identity-user): encoded address

---

lib/Account/AccountItem.js
lib/Identity/IdentityUser.js
lib/Identity/LinkIdentityUser.js
package.json
yarn.lock

fix: import dep path

---

lib/Account/Avatar.js
lib/Identity/IdentityUser.js
package.json
src/stories/Identity.stories.js
yarn.lock

close #30 
ref https://github.com/opensquare-network/collaboration/issues/847
- Avatar support ethereum avatar

fix(identity-user): sync logic

---

lib/Card/Card.js
lib/Card/types.ts
src/stories/Card.stories.js

feat(card): prop hoverable

---

lib/styled/Pagination.js

close #62 
only render necessary item

fix(pagination): performance

---

lib/Notification/index.js
lib/Notification/styled.js
lib/Notification/types.ts

feat(notification): add warning notification support

---

lib/styled/Pagination.js
src/stories/Pagination.stories.js

if only 1 page in total, disable the `lastPageItem`

fix(pagination): duplicated page 1

---

lib/styled/Button.js

https://github.com/opensquare-network/collaboration/issues/908
minus border width

fix(button): calc border padding

---

lib/Collapse/styled.js
lib/Icon/CaretDown.js

fix: collapse icon svg

---

lib/Select/Select.js
lib/Select/index.js
lib/Select/styled.js
lib/Select/types.ts
lib/index.js
src/stories/Select.stories.js

feat: select

---

lib/Select/styled.js

If this PR needed to release a new version, the **commit message format** following below:
- `feat: xxxxx`: will release minor version
- `fix: xxxxx`: will release patch version
Commit message format example: `feat(card): support ghost`.
And then merge this PR via **Square merge**.

fix(select): option offset

---

lib/styled/Dropdown.js
tsup.config.ts

Reverts opensquare-network/ui#83

fix: Revert "fix: dropdown import", remove emit dts

---

notify.mjs

fix: update package.json import to use readFileSync

fix: update package.json import to use readFileSync
